version: 1.0.{build}
image: Ubuntu
environment:
  DOCKER_USER:
    secure: iWRp0Mn2nb+UizxjgU02/w==
  DOCKER_PASS:
    secure: FG7GX9pJhL0L9et6XYYH9A4Uu0w6FBjSdPXaTNXTBiM=
    
for:
-
  branches:
    only:
      - master
  
  environment:
    IMAGE_TAG: latest
-
  branches:
    except:
      - master
    
  environment:
    IMAGE_TAG: "$APPVEYOR_REPO_BRANCH-latest"
    
install:
- sh: docker version    
- sh: echo "IMAGE_TAG=$IMAGE_TAG"
build_script:
- sh: >-
    docker build -t matr/mock-ae-csharp:$IMAGE_TAG -f _docker/alpine-x64.Dockerfile .
deploy_script:
- sh: >-
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    
    docker push matr/mock-ae-csharp:$IMAGE_TAG