version: 1.0.{build}
image: Ubuntu
#environment:
  #DOCKER_USER:
  #  secure: iWRp0Mn2nb+UizxjgU02/w==
  #DOCKER_PASS:
  #  secure: FG7GX9pJhL0L9et6XYYH9A4Uu0w6FBjSdPXaTNXTBiM=
    
for:
-
  branches:
    only:
      - master
  
  environment:
    IMAGE_TAG: latest
-
  branches:
    except:
      - master
    
  environment:
    IMAGE_TAG: "$APPVEYOR_REPO_BRANCH-latest"
    
before_build: 
  sh: >-
    docker network create --driver bridge testing-net
    
    docker run --rm -d -p 5672:5672 -p 15672:15672 --name rabbit --network testing-net rabbitmq:3.7.4-management-alpine    
build_script:
- sh:  >-
    echo IMAGE_TAG=$IMAGE_TAG
    
    printenv
    
    docker build --build-arg RABBIT_HOST_NAME=rabbit --network testing-net -t matr/mock-ae-csharp:$IMAGE_TAG -f _docker/alpine-x64.Dockerfile .
    
    mkdir test_results
    
    docker run -v ${PWD}/test_results:/host_test_results --rm --entrypoint cp matr/mock-ae-csharp:$IMAGE_TAG -r test_results/test_results.xml /host_test_results
deploy_script:
- sh: >-
    echo "$APPVEYOR_JOB_ID"
    
    echo "$APPVEYOR_API_URL"
    
    #curl -v -F 'file=test_results/test_results.xml' https://ci.appveyor.com/api/testresults/mstest/$APPVEYOR_JOB_ID
    
    testresult
    
    curl -v -F 'file=test_results/test_results.xml' $APPVEYOR_API_URLtestresults/mstest/$APPVEYOR_JOB_ID
    
    docker login -u="$DOCKER_USER" --password-stdin <<<$DOCKER_PASS
    
    docker push matr/mock-ae-csharp:$IMAGE_TAG