version: 1.0.{build}
image: Ubuntu
environment:
  DOCKER_USER:
    secure: iWRp0Mn2nb+UizxjgU02/w==
  DOCKER_PASS:
    secure: ry77cwLerXuAOhHD4Azlfg==
install:
- sh: >-
    docker version    
build_script:
- sh: >-
    docker build -t ausarb/mock-ae-csharp:latest -f _docker/alpine-x64.Dockerfile .
deploy_script:
- sh: >-
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push ausarb/mock-ae-csharp:latest